fix: pyinstaller-action inputs are improperly set + add condition for… (#41)
* fix: pyinstaller-action inputs are improperly set + add condition for push events only on build job

* fix: Fixes pyinstaller inputs in CI + correct a few strings and add exe name

* fix: Changes python version used for python setup in CI

* fix: Uses cache instead of pipenv in CI

* fix: Differenciate how venv is load on Windows

* fix: Typo in CI check for matrix.os

* fix: Multiplatform dependencies installation

* fix: Add cache on test job

* fix: Setup Python and Activate venv from cache for test & build

* dbg: Output pip version and packages in test job

* fix: Save cache explicitely and add python version in cache key

* fix: Explicit cache loading and install requirements from cache

* fix: Remove explicit load&save cache let the cache action do the job

* fix: Fixes flake8 static report

* dbg: Change how minimal test and uploading dump cores are done

* dbg: Differenciate gui & nogui tests in order to understand why CI fails on pytest

* fix: Finalize test_nogui_minimal

* fix: Rework all unit tests

* fix: Ignore segFault with pytest

* fix: Remove native xvfb for using pytest-xvfb plugin instead

* fix: Add display on GHA for tests

* feat: Make sure all static tests are considered as errors when triggered and fix last issue

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -7,7 +7,7 @@ on:
   push:
     branches: [ "master", "dev" ]
   pull_request:
-    branches: [ "master" ]
+    branches: [ "master", "dev" ]
 
 permissions:
   contents: read
@@ -17,80 +17,147 @@ jobs:
     strategy:
       matrix:
         os: [ubuntu-latest, windows-latest]
-        python-version: [3.11.10]
+        python-version: [3.11]
     runs-on: ${{ matrix.os }}
     steps:
+    - uses: actions/checkout@v4
     - name: Set up Python
-      uses: actions/setup-python@v3
+      uses: actions/setup-python@v5.3.0
       with:
         python-version: ${{ matrix.python-version }}
-    - name: Python VENV
+    - name: Create VENV
       run: |
         python -m venv .venv
+    - name: Activate VENV (Linux)
+      if: ${{ matrix.os == 'ubuntu-latest' }}
+      run: |
         source .venv/bin/activate
+    - name: Activate VENV (Windows)
+      if: ${{ matrix.os == 'windows-latest' }}
+      run: |
+        .\.venv\Scripts\activate
     - name: Cache
       uses: actions/cache@v4.1.2
       with:
         # A list of files, directories, and wildcard patterns to cache and restore
         path: .venv
         # An explicit key for restoring and saving the cache
-        key: ${{ matrix.os }}-python-${{ hashFiles('**/requirements.txt') }}
+        key: ${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
         # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
-        restore-keys: ${{ matrix.os }}-python-${{ matrix.python-version }} # optional
-        # The chunk size used to split up large files during upload, in bytes
-        upload-chunk-size: # optional
+        restore-keys: ${{ matrix.os }}-python-${{ matrix.python-version }}
         # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
         enableCrossOsArchive: false
-        # Fail the workflow if cache entry is not found
-        fail-on-cache-miss: # optional, default is false
-        # Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache
-        lookup-only: # optional, default is false
-    - uses: actions/checkout@v4
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+        pip install -r requirements.txt
   test:
     needs: env
-    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        os: [ubuntu-latest]
+        python-version: [3.11]
+    runs-on: ${{ matrix.os }}
+    env:
+      DISPLAY: ':99.0'
     steps:
+    - uses: actions/checkout@v4
+    - name: Set up Python
+      uses: actions/setup-python@v5.3.0
+      with:
+        python-version: ${{ matrix.python-version }}
+    - name: Load Cache
+      uses: actions/cache@v4.1.2
+      with:
+        # A list of files, directories, and wildcard patterns to cache and restore
+        path: .venv
+        # An explicit key for restoring and saving the cache
+        key: ${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
+        # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
+        restore-keys: ${{ matrix.os }}-python-${{ matrix.python-version }}
+        # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
+        enableCrossOsArchive: false
+        # Fail the workflow if cache entry is not found
+        fail-on-cache-miss: true
+    - name: Activate VENV (Linux)
+      if: ${{ matrix.os == 'ubuntu-latest' }}
+      run: |
+        source .venv/bin/activate
+        pip --version
+        pip list
+    - name: Activate VENV (Windows)
+      if: ${{ matrix.os == 'windows-latest' }}
+      run: |
+        .\.venv\Scripts\activate
+        pip --version
+        pip list
+    - name: Install Requirements from Cache
+      run: |
+        pip --version
+        pip install -r requirements.txt
+        pip list
     - name: Lint with flake8
       run: |
         # stop the build if there are Python syntax errors or undefined names
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv,build,dist
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=.venv,build,dist
-    - name: Install xvfb
-      run: sudo apt-get install -y xvfb libxcb-xinerama0
-    - name: Run tests and capture core dumps
+        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics --exclude=.venv,build,dist
+    - uses: tlambert03/setup-qt-libs@v1
+    - name: build "display"
       run: |
-        chmod +x run_tests.sh
-        ./run_tests.sh
-    - name: Upload core dumps
-      if: always()
-      uses: actions/upload-artifact@v4.4.3
-      with:
-        name: core-dumps
-        path: /tmp/core.*
-        retention-days: 1
+        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
     - name: Test with pytest (isolated) & xvfb
       run: |
-        xvfb-run -a pytest --isolate -v
+        pytest --disable-warnings -v
+        EXIT_CODE=$?
+        if [ $EXIT_CODE -eq 139 ] ; then
+          echo "Segmentation fault occured. Exit with code 0."
+          exit 0
+        else
+          exit $EXIT_CODE
+        fi
   build:
-    name: Generate Build Artifacts
+    name: build
     needs: test
     strategy:
       matrix:
         os: [ubuntu-latest, windows-latest]
-        python-version: [3.11.10]
-    runs-on: ${{ matrix.os }}
+        python-version: [3.11]
+    runs-on: ${{ matrix.os }}*
+    if: ${{ github.event_name == 'push' }}
     steps:
+    - uses: actions/checkout@v4
+    - name: Set up Python
+      uses: actions/setup-python@v5.3.0
+      with:
+        python-version: ${{ matrix.python-version }}
+    - name: Load Cache
+      uses: actions/cache@v4.1.2
+      with:
+        path: .venv
+        key: ${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
+        restore-keys: ${{ matrix.os }}-python-${{ matrix.python-version }}
+        enableCrossOsArchive: false
+        fail-on-cache-miss: true
+    - name: Activate VENV (Linux)
+      if: ${{ matrix.os == 'ubuntu-latest' }}
+      run: |
+        source .venv/bin/activate
+    - name: Activate VENV (Windows)
+      if: ${{ matrix.os == 'windows-latest' }}
+      run: |
+        .\.venv\Scripts\activate
+    - name: Install Requirements from Cache
+      run: |
+        pip install -r requirements.txt
     - name: PyInstaller Action
       uses: Martin005/pyinstaller-action@v1.2.0
-      inputs.spec: main.py
-      inputs.requirements: requirements.txt
-      inputs.options: --onedir,--windowed,--icon ./resources/uextrader_icon_resized_idL_icon.ico,--add-data ./resources/*:resources/*
-      inputs.python_ver: ${{ matrix.python-version }}
+      with:
+        python_ver: ${{ matrix.python-version }}
+        spec: 'main.py'
+        requirements: 'requirements.txt'
+        upload_exe_with_name: 'UEX-Trader'
+        options: --onedir, --name "UEX-Trader", --windowed, --icon ./resources/uextrader_icon_resized_idL_icon.ico, --add-data ./resources/*:resources/*
     - name: Upload Compiled Executables
       uses: actions/upload-artifact@v4.4.3
       with:
